Smaller profile bugs
twali-xyz/twali-xyz pull request #12
Opened 2022-02-16 19:06 UTC by hone1er

Added social media URLs in profile

Changed current title placeholder to be 'current title' from 'current company title'

# Handling links question
Should the URLs open the social media pages in a new tab using _blank? This can increase page view time because it prevents the page from being closed when the social media links are clicked

2022-02-18 18:16 UTC, nagmak requested changes

2022-02-18 19:30 UTC, nagmak commented on components/Profile/Profile.tsx
> +    twitter?: string;
Perfect thanks for the icons!

Gotcha! When I was checking the ceramic data that was being returned after Profile Builder it only had twitterUsrName and linkedInUsrName with empty fields returning. When the data is updating to ceramic, you're able to send in new fields too, so it's possible the twitter and linkedin ones were created after saving the modal.

But appreciate you taking a look either way! I may be off haha.

2022-02-22 08:38 UTC, hone1er commented on components/Profile/Profile.tsx
> +    twitter?: string;
I see where it's coming from now. When the user signs up they have the option to input their usernames and that gets saved to twitterUsrName & linkedInUsrName

If we only want to keep one option (e.g. twitterUsrName or twitter, linkedInUsrName or linkedIn) we have a few options:
- keep username inputs while signing up as is, concat the usernames with twitter.com/ and linkedIn.com/ respectively either when saved to profile or when inserting into UI, and change the edit profile to receive usernames instead of URLs as well for consistency
- change username inputs while signing up to be social media URL inputs, similar to the current edit profile modal


Would love to get some feedback on what y'all think is best.


Going to commit my current changes with the icons instead of text URL links for now

2022-02-22 17:18 UTC, nagmak commented on components/Profile/Profile.tsx
> +    twitter?: string;
Based on our discussion on the call today - totally support letting users sign up with URLs for their socials for consistency. Thanks!

2022-02-23 18:25 UTC, nagmak approved these changes
LGTM! woooo✨

2022-02-23 18:26 UTC, merged