1121: Add correct user permissions to let only the expert role apply to a project
twali-xyz/twali-xyz pull request #122
Opened 2022-08-08 18:50 UTC by nagmak

### What changes were made?

- Added "expert" and "client" roles
- Added a proposal application date
- Hid 'Post a Job' if the account type is expert
- project page permissions were restricted by roles as well
- SOW builder is restricted to clients only

### Is there any background info about the change?

- to ensure clients and experts see a different view of the marketplace, SOW builder and project page

### Are there any state changes? Mention key ones (if any)
NA

### Screenshots or Gifs✨

### Any new dependencies? Why were they added?
NA

### Shortcut Link

https://app.shortcut.com/twali/story/1121/add-correct-user-permissions-to-let-only-the-expert-role-apply-to-a-project

2022-08-08 20:25 UTC, NickGonzalez04 commented on components/Project/ProjectDetails.tsx
>  const ProjectDetails = (props) => {
I don't see any other use of props in the file since we are using `useBounty()` and `useUser`. (i could be wrong but just double checking!

2022-08-08 20:30 UTC, NickGonzalez04 commented on utils/walletUtils.tsx
> +        console.log(userData);
🔫 🔫

2022-08-08 20:31 UTC, NickGonzalez04 approved these changes
Other than the `props` comment. Looks gucci to go!

2022-08-09 14:43 UTC, nagmak commented on components/Project/ProjectDetails.tsx
>  const ProjectDetails = (props) => {
ooo I'll double check!

2022-08-09 14:44 UTC, nagmak commented on utils/walletUtils.tsx
> +        console.log(userData);
🫡🫡

2022-08-09 15:10 UTC, hone1er requested changes

2022-08-09 15:10 UTC, hone1er commented on components/Project/ProjectDetails.tsx
> +            to={userState?.accType === "Client" ? "client": "view"}
Also this one. My bad i did not realize these were being saved capitalized 🤦‍♂️

There are a few more so wherever there is a new userpermissionrestricted component, it should be set to ?.toLowerCase = "client" (or "expert")

2022-08-09 18:32 UTC, nagmak commented on components/Project/ProjectDetails.tsx
> +            to={userState?.accType === "Client" ? "client": "view"}
oooh yeah it's kind of a mess with the old and new versions so I'll just lowercase everything and check

2022-08-09 20:38 UTC, merged