Migrate Profiles from ceramic to use dynamoDB: Part 2 - Update user
twali-xyz/twali-xyz pull request #33
Opened 2022-03-16 22:13 UTC by nagmak

### What changes were made?

- Added 3 endpoints to update user in the backend: experience, company and profile
    - 3 endpoint functions: `updateUserProfile`, `updateUserExperience`, `updateUserCompanyData`
- Allows users to add or edit the three areas of their profile

### Is there any background info about the change?

- As part of migration from ceramic to dynamoDB

### Are there any state changes? Mention key ones (if any)

```
setCompanyData({
      ...companyData,
      [evt.target.name]: evt.target.value
    });
```

### Screenshots or Gifs✨

### Any new dependencies? Why were they added?

NA

### Shortcut Link

https://app.shortcut.com/twali/story/335/migrate-profiles-from-ceramic-to-use-dynamodb

2022-03-18 23:18 UTC, nagmak commented
@NickGonzalez04 @hone1er I've updated with all the new changes! pls review and lmk if there's anything to fix :)

2022-03-19 01:46 UTC, NickGonzalez04 commented on data/dynamodb.js
> +const AWS = require("aws-sdk");
Was this not working inside the function?

2022-03-19 01:49 UTC, NickGonzalez04 commented on data/dynamodb.js
> +                ":updatedData": updatedCompanyData,
LFGGGGGGGG 🚀

2022-03-19 01:51 UTC, NickGonzalez04 requested changes
PR is GREAT!! One ask, could you change the TableName back to `dev_staging_user_profile_test` ?

2022-03-19 04:02 UTC, nagmak commented on data/dynamodb.js
> +const AWS = require("aws-sdk");
ah this is a remnant from the marshalling stuff, i'll move it back

2022-03-19 04:05 UTC, nagmak commented
@NickGonzalez04 done!

2022-03-19 04:08 UTC, NickGonzalez04 approved these changes
MF merging this on Friday! Riskkkkkkkyyyy

2022-03-19 04:09 UTC, merged