Marketplace backend
twali-xyz/twali-xyz pull request #67
Opened 2022-05-10 17:19 UTC by hone1er

### What changes were made?

- Functional filtering of marketplace contracts

### Is there any background info about the change?

- mostly backend changes to implement filtering
- Should allow for OR filtering within categories, as well as AND filtering between categories
- All filters should be functional
- sorting still needs to be completed

### Are there any state changes? Mention key ones (if any)

NA

### Screenshots or Gifs✨

<img width="1512" alt="Screen Shot 2022-05-10 at 10 17 18 AM" src="https://user-images.githubusercontent.com/24376928/167685664-679d6fdb-d2ba-499a-bd8a-1b5b03c1b419.png">
<img width="1512" alt="Screen Shot 2022-05-10 at 10 17 12 AM" src="https://user-images.githubusercontent.com/24376928/167685677-4139aa65-6847-4f3b-a247-f578f168b8f8.png">
<img width="1512" alt="Screen Shot 2022-05-10 at 10 17 08 AM" src="https://user-images.githubusercontent.com/24376928/167685682-8b60ae12-3fa0-4f78-8bbb-93e3975e3438.png">
<img width="1512" alt="Screen Shot 2022-05-10 at 10 17 00 AM" src="https://user-images.githubusercontent.com/24376928/167685693-1545423c-469a-4a67-8921-2dacccb2b43c.png">
<img width="1512" alt="Screen Shot 2022-05-10 at 9 59 46 AM" src="https://user-images.githubusercontent.com/24376928/167685699-1e67ce05-2743-4d73-ab8a-3e8ac5aa68d4.png">
<img width="1512" alt="Screen Shot 2022-05-10 at 9 58 06 AM" src="https://user-images.githubusercontent.com/24376928/167685707-66691170-cd6c-4522-b25c-87e5600cd497.png">

### Any new dependencies? Why were they added?

NA

### Shortcut Link

https://app.shortcut.com/twali/story/850/complete-marketplace-filters

2022-05-10 20:39 UTC, nagmak requested changes

2022-05-10 20:39 UTC, nagmak commented on next.config.js
> +    TABLE_NAME: "market_contracts",
For production, do we need to add another table to the environment along with our `dev_staging_user_profile_test` table? Or do we remove `market_contracts` and revert back to the original table. @hone1er @NickGonzalez04

2022-05-10 20:39 UTC, nagmak commented on public/newMarketTest.csv
> +,title,description,client,type,start_date,end_date,duration,token,amount,converted_amount,due_date,created_on,industry,expertise,status,attachments,contract_id
I think it might be better if we create a folder under the already existing `test` folder, and potentially call it `mock-data` to keep everything a bit more organized. What do you think? @hone1er

2022-05-10 20:55 UTC, hone1er commented on public/newMarketTest.csv
> +,title,description,client,type,start_date,end_date,duration,token,amount,converted_amount,due_date,created_on,industry,expertise,status,attachments,contract_id
I might need to consult you on how that's done lol but overall sounds good to me

2022-05-10 21:02 UTC, hone1er commented on next.config.js
> +    TABLE_NAME: "market_contracts",
Ah i have an update on that. I'll fix it. It'll be two tables so it will have to export 2 table names. So i'll have to put ```{TABLE_NAME: "dev_staging_user_profile_test",
CONTRACTS: "market_contracts}```

and import both into the dynamoDB file.

I'll make that change along with moving the file

2022-05-11 13:25 UTC, NickGonzalez04 commented on next.config.js
> +    TABLE_NAME: "market_contracts",
We can create it as one table still so it can have a relationship with a user by contract ID. I wanted to change the table name to have a better backend naming convention.

2022-05-11 20:10 UTC, nagmak commented on next.config.js
> +    TABLE_NAME: "market_contracts",
Okay awesome! Thanks! Also let's have that table/backend discussion soon too

2022-05-18 20:41 UTC, NickGonzalez04 requested changes
🤏 small naming change. SORRY JOE!!!

2022-05-18 20:41 UTC, NickGonzalez04 commented on components/Marketplace/BountyList.tsx
> +                due_date,
oneeee small change I just remembered 🤏 . can we update `due_date` => `application_deadline`? All `due_dates` to be `application_deadline. 

due_date seemed broad. Was a last minute change this afternoon with contract variable state reviewing.

2022-05-18 20:41 UTC, NickGonzalez04 commented on components/Marketplace/BountyList.tsx
> +                    due_date={due_date}
+1

2022-05-18 20:41 UTC, NickGonzalez04 commented on infrastructure/scripts/putItem_contract.py
> +            "due_date": 1665014400,
+1

2022-05-19 14:12 UTC, NickGonzalez04 reviewed
I ran into a couple UI bugs on the filter review on my end. If i selected an Industry or Expertise option the filter it wouldn't populate that i selected it and the chip wouldn't have any text in it.

![Screen Shot 2022-05-19 at 10 00 05 AM](https://user-images.githubusercontent.com/48919838/169313969-630e8fbd-e752-4063-acb6-a0e5dcb406c3.png)
![Screen Shot 2022-05-19 at 10 01 50 AM](https://user-images.githubusercontent.com/48919838/169314000-808a3590-e266-480b-a965-e38bedb2ed6b.png)
![Screen Shot 2022-05-19 at 10 01 58 AM](https://user-images.githubusercontent.com/48919838/169314039-3d1e6094-c454-43b1-8bf1-686c3739d195.png)

2022-05-19 21:40 UTC, NickGonzalez04 approved these changes
Ovvvveerrrdueee Approve!

2022-05-19 21:40 UTC, merged