Wait for 848, then merge this: 767 - Create Werk Modal & User Permissions, Connect Wallet
twali-xyz/twali-xyz pull request #74
Opened 2022-05-26 21:41 UTC by nagmak

### What changes were made?

- Added a werk modal for posting a job on Marketplace
- Added User Permissions to marketplace, and SOW builder, and changed the Connect wallet flow to include a logged out message

### Is there any background info about the change?

- Will ensure users can log in if they refresh the page or disconnect from the site on any page that uses this flow

### Are there any state changes? Mention key ones (if any)

A few refactored ones

### Screenshots or Gifs✨
<img width="1436" alt="Screen Shot 2022-05-26 at 2 40 24 PM" src="https://user-images.githubusercontent.com/16668970/170584670-68154076-557a-4aa9-bbfa-44cfd8e0749b.png">
<img width="1432" alt="Screen Shot 2022-05-26 at 2 39 43 PM" src="https://user-images.githubusercontent.com/16668970/170584690-3053e72d-d5f3-4da7-8afe-0cd9c8f3aee6.png">
<img width="1440" alt="Screen Shot 2022-05-26 at 2 39 58 PM" src="https://user-images.githubusercontent.com/16668970/170584686-92b51c72-c053-422a-8780-67aa36283a73.png">

### Any new dependencies? Why were they added?

NA

### Shortcut Link

https://app.shortcut.com/twali/story/853/user-permissions-connect-wallet-on-sow-builder-flow
https://app.shortcut.com/twali/story/767/sow-create-werk-modal

2022-05-27 02:24 UTC, NickGonzalez04 commented on components/Marketplace/SortBounty.tsx
> +
Has merge conflict here with the options below on line 15 and 16. I think the branch just needs to be updated with the recent changes for merged PRs into staging.

2022-05-27 02:26 UTC, NickGonzalez04 requested changes
Wanted to see if you needed to pull in new PR's that were merged and check to make sure it was still functioning on your end.

2022-05-31 14:07 UTC, NickGonzalez04 requested changes
Other than the button sizing in the`MarketPlace` page this is good to go!! Love it!

2022-05-31 14:07 UTC, NickGonzalez04 commented on components/Project/Project.tsx
> -              whichPage="profile"
Never mind, I see in the `create-werk.tsx` where this is set for the HeaderNav. Disregard!

2022-05-31 19:38 UTC, nagmak commented on components/Marketplace/SortBounty.tsx
> +                width={"309px"}
LOL i see it now, aight i shall fix it ty for catching that

2022-06-01 00:07 UTC, nagmak commented
<img width="1440" alt="Screen Shot 2022-05-31 at 8 05 12 PM" src="https://user-images.githubusercontent.com/16668970/171303157-194fde7a-7478-42fe-bbd1-d04bf67e3cf3.png">

Made the change, looks like it's fixed on my end now @NickGonzalez04

2022-06-01 00:28 UTC, NickGonzalez04 commented
🔥🔥 Will do a once through again and approve but awesome!

2022-06-01 02:36 UTC, NickGonzalez04 approved these changes
Approval is good!

2022-06-01 02:36 UTC, merged